### PR TITLE
Added Footer & fixed styling issues

### PR DESCRIPTION
**Pull request by siddheshhr**
added a footer by updating a footer.ejs   
Also fixed styling issue of the text above the footer 

Created a new pull request to fix the conflict changes check  #232

### CODE REVIEW

**Review by Ultimateutkarsh11 — APPROVED** [review]

**Comment by pallavisavant** [comment]
added a footer by updating a footer.ejs 
Also fixed styling issue of the text above the footer

It would be more clearer if you could add before and after changes screenshot of UI. @siddheshhr

**Comment by pallavisavant** [comment]
Was this issue already existing? If yes then can you link it to PR?
If not then @goyalh4164 is it required that contributors to log the issue/improvements first before raising a PR ?

**Comment by siddheshhr** [comment]
> added a footer by updating a footer.ejs Also fixed styling issue of the text above the footer
> 
> It would be more clearer if you could add before and after changes screenshot of UI. @siddheshhr

UPDATED IMAGE :
image

OLD IMAGE:
Opera Snapshot_2024-05-24_213852_note-vault-tkco onrender com

**Comment by siddheshhr** [comment]
> Was this issue already existing? If yes then can you link it to PR? If not then @goyalh4164 is it required that contributors to log the issue/improvements first before raising a PR ?

there were not any issues regarding the footer.I had inquired on the discord community and it had said you can create a pull request not present in the issues @pallavisavant

**Comment by goyalh4164** [comment]
> Was this issue already existing? If yes then can you link it to PR? If not then @goyalh4164 is it required that contributors to log the issue/improvements first before raising a PR ?

@pallavisavant contributors just need to attach the issue number

**Review by VaibhavArora314 — APPROVED** [review]

**Review by goyalh4164 — APPROVED** [review]

**Pull request merged**
