### PR TITLE
Header and dark, light mode icon fixed

### PR DESCRIPTION
**Pull request by chaanakyaaM**
Closes Issue: #436 

Header elements are now fixed .

Screenshot (245)

The sun and moon icons when toggled from light mode to dark more are fixed.

Screenshot (244)

Screenshot (243)

Let me know if there are any changes to be made...

### CODE REVIEW

**Review by VaibhavArora314 — APPROVED** [review]

**Comment by VaibhavArora314** [comment]
resolve merge conflicts

**Comment by chaanakyaaM** [comment]
ok

**Review by Ultimateutkarsh11 — APPROVED** [review]

**Comment by chaanakyaaM** [comment]
Done !

**Comment by chaanakyaaM** [comment]
Issue resolved.
Could you please review the PR.

**Comment by chaanakyaaM** [comment]
Would you kindly add gssoc and level1 label.
Thank you.

**Pull request merged**
