### PR TITLE
Added contact link: Issue#456

### PR DESCRIPTION
**Pull request by ParnaRoyChowdhury777**
I have added the contact link in the footer and navbar. 

Fix : #456

### CODE REVIEW

**Comment by VaibhavArora314** [comment]
Link the respective issue.

**Review by goyalh4164 — APPROVED** [review]

**Review by VaibhavArora314 — APPROVED** [review]

**Comment by goyalh4164** [comment]
@ParnaRoyChowdhury777 resolve the merge conflicts

**Comment by ParnaRoyChowdhury777** [comment]
> @ParnaRoyChowdhury777 resolve the merge conflicts

resolved conflicts

**Review by Ultimateutkarsh11 — APPROVED** [review]

**Comment by goyalh4164** [comment]
@ParnaRoyChowdhury777 still conflicts exists

**Pull request merged**
