### PR TITLE
Folder Structure Updated

### PR DESCRIPTION
**Pull request by MitulSonagara**
@Ultimateutkarsh11 I have updated the whole folder structure and also double checked the working of the site as it is.

Issue No #22 

Please review it and let me know if there is any changes.
It will be very helpful if you give me level2 badge for this.

### CODE REVIEW

**Comment by goyalh4164** [comment]
@MitulSonagara just put the server.js file out of source because it is the entry point of the deployment and also change the dev script according to that in the package.json and then just do final check .. rest of the things are good

**Comment by Ultimateutkarsh11** [comment]
@MitulSonagara just do the required changes mentioned above, rest is good.

**Comment by VaibhavArora314** [comment]
ss

@MitulSonagara

**Comment by VaibhavArora314** [comment]
can u open a seperate pr with changes @MitulSonagara , I have reverted this pr.

**Pull request merged**
