### PR TITLE
scrollbar update

### LINKED ISSUE #341: Feat: Scroll Bar
### Describe the feature

Changing the UI for current scrollbar. The default blue colour doesn't match with the website. Changing it to red colour theme would be better.

Adding functionality - Visible only when user is scrolling and disable when page is still. It will optimize the UI of website

### Add ScreenShots

Screen Shot 2024-05-31 at 9 42 41 PM

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by hars-21**
Fixes #341 

I have successfully changed the UI of scrollbar according to the theme of the website. It has been changed from default to custom style. Also, a functionality has been added to make hidden when user is not scrolling and only appear when user scrolls the page just like in github.
Screen Shot 2024-06-06 at 10 15 18 PM
Screen Shot 2024-06-06 at 10 15 20 PM

### CODE REVIEW

**Review by VaibhavArora314 — APPROVED** [review]

**Comment by VaibhavArora314** [comment]
resolve merge conflicts

**Comment by hars-21** [comment]
@VaibhavArora314 REsolved

**Comment by goyalh4164** [comment]
@hars-21 still merge conflicts exist in style.css file

**Comment by hars-21** [comment]
@goyalh4164 Done

**Review by Ultimateutkarsh11 — APPROVED** [review]

**Review by goyalh4164 — APPROVED** [review]

**Pull request merged**
