### PR TITLE
Fixed : Space removed in signup and login page

### PR DESCRIPTION
**Pull request by BHS-Harish**
**Issue #105 Fixed**

Extra space removed in login and signup page.

**Screenshot**

Before 

Screenshot 2024-05-14 234041

After

image

### CODE REVIEW

**Comment by Ultimateutkarsh11** [comment]
Looks good to me.

**Review by goyalh4164 — COMMENTED** [review]
Code looks good

**Comment by BHS-Harish** [comment]
Thank you both of you @Ultimateutkarsh11 @goyalh4164

**Comment by goyalh4164** [comment]
@BHS-Harish Welcome... Your changes are live now you can open the production link

**Pull request merged**
