### PR TITLE
Hamburger button added for smaller screens

### PR DESCRIPTION
**Pull request by Ayushk3**
issue #177 
Screenshot 2024-05-18 at 2 13 11 PM

### CODE REVIEW

**Comment by Ayushk3** [comment]
I had tried to resolve merge conflict that was arising earlier, if yet not resolved then please let me know .So, that I can work on further

**Review by Ultimateutkarsh11 — APPROVED** [review]

**Review by VaibhavArora314 — APPROVED** [review]

**Review by goyalh4164 — APPROVED** [review]

**Comment by VaibhavArora314** [comment]
resolve merge conflicts

**Comment by Ultimateutkarsh11** [comment]
@Ayushk3 any updates?

**Comment by Ayushk3** [comment]
> @Ayushk3 any updates?

Sir, I will complete it by tonight.

**Comment by VaibhavArora314** [comment]
@Ayushk3 any updates?

**Comment by Ultimateutkarsh11** [comment]
@Ayushk3 I'm closing this PR for now, you can create a new one after updating files and resolving merge conflicts

**Pull request closed without merging**
