### PR TITLE
fixed what our client say section for Mobile

### PR DESCRIPTION
**Pull request by Utsavladia**
Fixed the carousel for mobile of what our client say to make it properly visible and enhance the user experience.

image

### CODE REVIEW

**Comment by pallavisavant** [comment]
Attach old and new UI screenshot.

**Comment by Utsavladia** [comment]
@pallavisavant 
I have attacked the old and new what our clients say section

## Old
image
## New
Screenshot 2024-06-02 205415

**Review by Ultimateutkarsh11 — APPROVED** [review]

**Review by VaibhavArora314 — APPROVED** [review]

**Comment by pallavisavant** [comment]
you got some conflicts, please resolve.

**Review by goyalh4164 — APPROVED** [review]

**Comment by Utsavladia** [comment]
@goyalh4164 @VaibhavArora314 
This merge did not get counted in my contribution to GSSoc
I think you will have to assing this pull also to me to make it get counted in my contributions.
Kindly assing this to me.

**Pull request merged**
