### PR TITLE
Fixed the why Note-Vault Page

### PR DESCRIPTION
**Pull request by SadafKausar2025**
Fixed issue: #348

before
Screenshot (1850)

after
Screenshot (1857)

Screenshot (1858)

### CODE REVIEW

**Comment by SadafKausar2025** [comment]
hello @pallavisavant 
please review this and merge my PR

**Comment by pallavisavant** [comment]
> hello @pallavisavant please review this and merge my PR

Tittle included would make it more readable , like "Why choose notevault" that was in older version

**Comment by SadafKausar2025** [comment]
title is also there
Screenshot (1866)

Screenshot (1867)

**Comment by SadafKausar2025** [comment]
hello @pallavisavant 
now is it correct?

**Review by pallavisavant — APPROVED** [review]

**Comment by SadafKausar2025** [comment]
hi @goyalh4164 @Ultimateutkarsh11 
can you please review this PR and merge it

**Review by Ultimateutkarsh11 — APPROVED** [review]

**Review by goyalh4164 — APPROVED** [review]

**Comment by SadafKausar2025** [comment]
hello @Ultimateutkarsh11 
please merge this PR

**Review by Ultimateutkarsh11 — APPROVED** [review]

**Comment by Ultimateutkarsh11** [comment]
@SadafKausar2025 please be patient and let other mentors approve this PR, then only it can be merged

**Comment by SadafKausar2025** [comment]
ok

**Review by goyalh4164 — APPROVED** [review]

**Comment by SadafKausar2025** [comment]
Hello @VaibhavArora314
Please approved this pr and merge it

**Comment by pallavisavant** [comment]
@SadafKausar2025  note that after your changes are ready to be reviewed, you need to assume a minimum of 2-3 days within which you are going to hear back. 

There is no need to tag everyone in the comments. Mentors are aware, and since some are handling multiple projects, there might be occasional delays. Please be mindful of this.

Thanks for understanding.

**Review by pallavisavant — APPROVED** [review]

**Comment by SadafKausar2025** [comment]
Ok understood mam
Mam please give levels also in this pr

**Pull request merged**
