### PR TITLE
Added password show hide functionality

### PR DESCRIPTION
**Pull request by piyush-gpt**
solves issue #139 

added password hide and show functionality.

Now users can hide as well as see their password, improving user experience

Screenshot 2024-05-18 105954

### CODE REVIEW

**Comment by VaibhavArora314** [comment]
Instead of writing hide text, can u add an eye icon

**Review by goyalh4164 — COMMENTED** [review]
@piyush-gpt everything is good just add an eye icon instead of text

**Comment by Ultimateutkarsh11** [comment]
@piyush-gpt any updates on the eye icon?

**Comment by piyush-gpt** [comment]
@Ultimateutkarsh11  yes, I will update this PR

**Comment by piyush-gpt** [comment]
@Ultimateutkarsh11  did it

**Review by VaibhavArora314 — APPROVED** [review]

**Review by Ultimateutkarsh11 — APPROVED** [review]

**Review by goyalh4164 — APPROVED** [review]

**Pull request merged**
