### PR TITLE
Fixes #433 : Improved UI of Main Page

### LINKED ISSUE #433: BUG: Fixing and Improving the UI of whole Main Page
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

As discussed already in PR #402  I want to confirm that the UI of the main page of the website has undergone significant changes that need to be addressed. Additionally, I will make improvements wherever I see necessary. A video has been attached for further reference about the issue.

https://github.com/Note-Vault/Note-Vault/assets/153659573/baeb4d1a-43fe-4a9c-89de-1e8a2a519253

As a GSSoC'24 contributor, I want to work on this issue.

Thank You!

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by AkshitGarg24**
Fixes #433 

The UI of the main page has been significantly improved and enhanced for a better appearance. A video has been attached for your reference. To compare with the previous version, please check the issue where I have attached the video of the earlier view.

https://github.com/Note-Vault/Note-Vault/assets/153659573/4d330b7c-af92-4e18-867e-733b8c95ee42

Before merging the PR, kindly remember to add labels and include my name in the assignees section.

Thank you!

### CODE REVIEW

**Comment by goyalh4164** [comment]
@AkshitGarg24 kindly resolve the merge conflicts .. your work seems good

**Comment by AkshitGarg24** [comment]
Done @goyalh4164

**Comment by AkshitGarg24** [comment]
@goyalh4164 Please assign me this PR also.

Thank You!

**Comment by AkshitGarg24** [comment]
Also @goyalh4164, I've noticed that the changes are not yet visible on the main website. Could you check why this is the case? I need to see the updates so I can consider further improvements.

**Pull request merged**
