### PR TITLE
Testinomial section improved

### PR DESCRIPTION
**Pull request by AnanyaJain25**
## Description
Testinomials section was having overlaps.

## Related Issue
Resolving testimonials section #259
## Changes
Changes made in crousel, imrpoved its presentation with white backgroound and elegant next previous buttion 

## Type of PR

- [x] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Testing Instructions

Just run and check on browser.

## Impact Analysis

- [N] Breaking change: This change introduces breaking modifications.
- [Y] Non-breaking change: This change does not introduce breaking modifications.
- [N] Disrupts existing functionality: This change disrupts the functionality of existing features.
- [Y] Does not disrupt existing functionality: This change does not disrupt the functionality of existing features.

## Screenshots (if applicable)

https://github.com/Note-Vault/Note-Vault/assets/136808696/377fd515-fdeb-4419-b4ac-4415280b36a2

## Checklist
- [Y] I have tested the changes locally and they work as expected.
- [Y] I have updated the documentation if necessary.
- [Y] I have reviewed the code and ensured it follows project standards.
- [Y] All tests (if applicable) pass successfully.
- [Y] I have added myself to the list of contributors if this is a significant contribution.

### CODE REVIEW

**Comment by VaibhavArora314** [comment]
resolve merge conflicts, rest is good.

**Comment by AnanyaJain25** [comment]
resolved.

**Review by VaibhavArora314 — APPROVED** [review]

**Comment by AnanyaJain25** [comment]
@Ultimateutkarsh11 @pallavisavant  please approve my changes I can see some recent PR merges however mine has been pending from 2 days now. If new merges are made I will have to resolve conflicts each time. Please review this and tell if changes are required.

**Review by Ultimateutkarsh11 — APPROVED** [review]

**Review by goyalh4164 — APPROVED** [review]

**Comment by goyalh4164** [comment]
@pallavisavant do this ASAP

**Pull request merged**
