### PR TITLE
automate reminders

### PR DESCRIPTION
**Pull request by hars-21**
Added a cron job that will run daily and send automate response to every issue opened and that will send reminder to contributor. this will enhance workflow of the project.

### CODE REVIEW

**Review by VaibhavArora314 — CHANGES_REQUESTED** [review]
this can be a little hectic if they are being pinged daily. is it possible to do this after every 7 days of inactivity on the issue or like run this cron job once in a week?

**Review by hars-21 — COMMENTED** [review]
Cron job now set to run every sunday.

**Comment by hars-21** [comment]
Now the cron job will be running once a week i.e. Sunday

**Review by VaibhavArora314 — APPROVED** [review]

**Comment by pallavisavant** [comment]
I will wait for everyone to finish reviewing then merge. thanks

**Review by Ultimateutkarsh11 — APPROVED** [review]

**Review by goyalh4164 — APPROVED** [review]

**Pull request merged**
