### PR TITLE
Redesign Ui of notes section #223

### PR DESCRIPTION
**Pull request by dhruv389**
I have Changed Ui and Design of  notes section.

issue No: #223 

🔺 **Please Change The tag of this issue level1 to level-2 or level-3.**

Screenshot :
---
Screenshot 2024-05-24 020047

### CODE REVIEW

**Comment by dhruv389** [comment]
@FoxxPratikSau , @pallavisavant  


please checkout my this pull request.

**Review by dhruv389 — COMMENTED** [review]
completed task  - Redesign Ui of notes section

**Review by dhruv389 — COMMENTED** [review]
completed

**Review by Ultimateutkarsh11 — APPROVED** [review]

**Comment by dhruv389** [comment]
@pallavisavant ,

**Yes , i Can fix it,  One line require to add in Css**

**Review by VaibhavArora314 — APPROVED** [review]

**Review by goyalh4164 — APPROVED** [review]

**Comment by goyalh4164** [comment]
@dhruv389 your branch has merge conflicts

**Review by dhruv389 — COMMENTED** [review]
Fixed all conflicts .
i have to make some changes which i have made for testing purpose.
✅✅Now Try to Merge this pull request.

**Comment by dhruv389** [comment]
Hello @goyalh4164 , @pallavisavant , @Ultimateutkarsh11 ,    try to Merge this pull request. I have fixed all conflicts.

**Review by Ultimateutkarsh11 — CHANGES_REQUESTED** [review]
@dhruv389 .env.example file is still causing the merge conflicts, resolve it

**Review by dhruv389 — COMMENTED** [review]
fixed env file

**Review by dhruv389 — COMMENTED** [review]
fixed note.ejs

**Comment by dhruv389** [comment]
Can you  review this pull request . i  solved issue related to conflicts files.

**Review by Ultimateutkarsh11 — APPROVED** [review]

**Pull request merged**
