### PR TITLE
testimonials updated

### PR DESCRIPTION
**Pull request by hars-21**
#42 solved
UI enhancement achieved
Created testimonials page 
Added carousel animation
Screen Shot 2024-05-14 at 3 40 32 PM

Please review.

### CODE REVIEW

**Comment by VaibhavArora314** [comment]
resolve merge conflicts

**Comment by Ultimateutkarsh11** [comment]
@hars-21 resolve the merge conflicts in the views/home.ejs and views/partials/header.ejs folders.
The rest looks good to me.

**Comment by hars-21** [comment]
@Ultimateutkarsh11 merge conflicts resolved. Please review

**Comment by VaibhavArora314** [comment]
for now comment out linkedin and twitter socials
also in github put link of github repo

**Review by VaibhavArora314 — APPROVED** [review]
looks good

**Pull request merged**
