### PR TITLE
Added Email Verification

### PR DESCRIPTION
**Pull request by SamarthUrane**
Email Verification Added. After User register he/she will get OTP and have to verify using this OTP to access the application.
image
image

### CODE REVIEW

**Comment by SamarthUrane** [comment]
Solved Issue No. #393 under GSSOC'24. Please add gssoc and level label

**Review by VaibhavArora314 — APPROVED** [review]

**Review by Ultimateutkarsh11 — APPROVED** [review]

**Comment by pallavisavant** [comment]
you got some conflicts.

**Comment by SamarthUrane** [comment]
All Conflicts are resolved @pallavisavant @goyalh4164

**Comment by SamarthUrane** [comment]
Hey @pallavisavant please add gssoc and level badges

**Pull request merged**
