### PR TITLE
PDF_download feature

### PR DESCRIPTION
**Pull request by Cralsic123**
### New Feature: PDF Download
**Description**

The PDF download feature enables users to download all their notes in a single PDF file. This feature enhances the usability of the application by providing users with a convenient way to access their notes offline.

**Implementation Details
Backend Changes**
**New Route:**

A new route /note/download has been implemented on the backend to handle the PDF download request.

**PDF Generation:**

When a user requests to download their notes, the backend generates a PDF file containing all the notes associated with the user.

**PDF File Delivery:**

Once the PDF file is generated, it is sent as a response to the client-side request for download.
Frontend Changes

**New Button:**

A new button labeled "Download All Notes" has been added to the home page interface.

**Download Trigger:**

When the user clicks the "Download All Notes" button, a request is sent to the backend to initiate the PDF download process.

**Usage**

**Downloading Notes:**

On the home page, locate the "Download All Notes" button.
Click the button to trigger the download process.
Once the download is complete, the user can access their notes offline by opening the downloaded PDF file.
Technologies Used
Backend: Node.js, Express.js
Frontend: HTML, CSS, JavaScript
PDF Generation: PDFKit (Node.js library for PDF generation)

### CODE REVIEW

**Comment by VaibhavArora314** [comment]
i guess you forgot to update the code files since u have only added .DS store file

**Comment by VaibhavArora314** [comment]
also add some screenshots of the feature

**Comment by Cralsic123** [comment]
Oh yes
Wait Ill add the code files.

**Comment by goyalh4164** [comment]
@Cralsic123 code looks good but there is merge conflict in your branch first resolve it

**Comment by Cralsic123** [comment]
@goyalh4164 done the changes…
Can you look at it once?

**Comment by Cralsic123** [comment]
@goyalh4164 is the conflict solved now??

**Comment by Cralsic123** [comment]
@goyalh4164 Please can you confirm me if its working now?

**Comment by Cralsic123** [comment]
@VaibhavArora314 The conflicts are resolved now.

**Pull request merged**
