### PR TITLE
home page improved

### PR DESCRIPTION
**Pull request by harinisayani**
I have improved the home page to look beautiful.
Screenshot (87)

### CODE REVIEW

**Comment by VaibhavArora314** [comment]
refer the corresponding issue also

**Review by goyalh4164 — COMMENTED** [review]
@harinisayani upload the screenshot of the complete page with both dark mode and light mode working

**Comment by harinisayani** [comment]
Hi,
I am getting same result in dark mode also. I added background image to home page.

**Comment by goyalh4164** [comment]
@harinisayani but there is merge conflict in your branch in the views/home.ejs file .. first resolve it

**Comment by harinisayani** [comment]
Hi @goyalh4164,
I have resolved the conflicts.

**Review by VaibhavArora314 — APPROVED** [review]

**Comment by harinisayani** [comment]
Hi,
I have resolved the conflicts.

**Comment by harinisayani** [comment]
Hi,
I have resolved the conflicts.

**Comment by harinisayani** [comment]
Hi @goyalh4164 
I have resolved all the conflicts. 
Once please check it. If there is no conflicts will you please merge it.

**Review by Ultimateutkarsh11 — APPROVED** [review]

**Pull request merged**
