### PR TITLE
Create-Pull-Request-Template

### PR DESCRIPTION
**Pull request by anglerfishlyy**
**fixes#85**

**Description:**

* This pull request introduces a pull request template file to streamline the process of creating new pull requests within the repository. 

* By implementing a template, we aim to ensure that all pull requests contain essential information, enabling quicker review and more efficient collaboration between contributors and maintainers.

*  The template includes sections for providing a clear title, a concise description of the changes, a list of tasks completed, any relevant issue references, and additional context or considerations.

*  By utilizing this template, we strive to enhance transparency, consistency, and communication throughout the pull request review process, ultimately improving the overall quality and effectiveness of contributions to the project.

Let us together make NOTE-VAULT the best !!

thank you.

### CODE REVIEW

**Comment by VaibhavArora314** [comment]
why is Pull request template present inside issue template folder?

**Comment by anglerfishlyy** [comment]
For better organization , if all templates will be located at one place , it will be easy to see them all ,  instead of searching for  a template in the entire repository.

If you want , i will create it in a  separate file , how do you want it to be @VaibhavArora314 ?

**Comment by VaibhavArora314** [comment]
hey @anglerfishlyy , github docs says that for github to know about pull request template, keep it simply in .github folder or inside PULL_REQUEST_TEMPLATE folder in .github folder

**Review by anglerfishlyy — COMMENTED** [review]
Is it okay?

**Comment by anglerfishlyy** [comment]
I think it's required to add PR template as it's not there.

now : 
Screenshot (59)

After merging , the empty spaced will be filled with the template.

**Review by VaibhavArora314 — APPROVED** [review]

**Pull request merged**
