### PR TITLE
Fixed the carousel section ui

### PR DESCRIPTION
**Pull request by mukilan2815**
image

I have changed the ui of carousel

Close this under GSSOC'24

### CODE REVIEW

**Comment by pallavisavant** [comment]
Add old and new UI screenshot.

**Comment by mukilan2815** [comment]
Issue no #320  
You can refer her.

**Comment by pallavisavant** [comment]
> Issue no #320 You can refer her.

You got some conflicts, please resolve them.

**Comment by mukilan2815** [comment]
Resolved all the conflicts

**Comment by mukilan2815** [comment]
GSSOC'24 ??

**Pull request merged**
