### PR TITLE
Changed the cards title and view

### PR DESCRIPTION
**Pull request by PuR-vI**
I have updated the card view to a dynamic and engaing card format making changes in the css and html files.

### CODE REVIEW

**Review by PuR-vI — COMMENTED** [review]
Changes in the card view style

**Comment by goyalh4164** [comment]
@PuR-vI your branch has merge conflicts

**Comment by PuR-vI** [comment]
> @PuR-vI your branch has merge conflicts

i resolved them. kindly check

**Comment by VaibhavArora314** [comment]
Can you post some screenshots also

**Comment by PuR-vI** [comment]
> Can you post some screenshots also

yes sure

**Comment by PuR-vI** [comment]
https://github.com/Note-Vault/Note-Vault/assets/97090750/aea00f24-2f23-4db9-8d43-0147724b1d5f

**Review by Ultimateutkarsh11 — APPROVED** [review]
Looks good to me

**Review by VaibhavArora314 — APPROVED** [review]

**Comment by Ultimateutkarsh11** [comment]
@PuR-vI I have reverted this PR because it is disturbing the currently existing structure of the website:
image
As you can see, the "Why chose note vault?" section appears twice and also, the one you created is aligned vertically.
From next time onwards, run git pull before your commit and carefully check the changes you have made.
This will save time and effort for both you and us.

**Pull request merged**
