### PR TITLE
Change logo

### PR DESCRIPTION
**Pull request by Ridhima10**
hello PA @Ultimateutkarsh11 ,
Issue resolved - #47 

Screenshot 2024-05-18 110502

Kindly merge it with main
Best Regards

### CODE REVIEW

**Review by VaibhavArora314 — CHANGES_REQUESTED** [review]
do not delete .env.example

**Comment by Ridhima10** [comment]
@VaibhavArora314  .env.example is not deleted . It is renamed to .env only

**Comment by VaibhavArora314** [comment]
> @VaibhavArora314 .env.example is not deleted . It is renamed to .env only

You do not need to push the changes to .env or .env.example files as they may cause problem when deploying the website

**Review by VaibhavArora314 — APPROVED** [review]

**Review by Ultimateutkarsh11 — APPROVED** [review]

**Comment by Ridhima10** [comment]
@Ultimateutkarsh11 @VaibhavArora314 @goyalh4164  kindly add labels

**Review by goyalh4164 — APPROVED** [review]

**Pull request merged**
