### PR TITLE
Added new icons in Navbar links

### PR DESCRIPTION
**Pull request by SadafKausar2025**
these icons beautify the page

before
Screenshot 2024-05-21 132117

after
Screenshot 2024-05-21 131714

### CODE REVIEW

**Comment by SadafKausar2025** [comment]
hi 
can you please merge this PR?

**Comment by SadafKausar2025** [comment]
hi @goyalh4164 
can you please merge this PR ?
I want to contribute more in this project

**Review by VaibhavArora314 — APPROVED** [review]

**Review by goyalh4164 — APPROVED** [review]

**Comment by VaibhavArora314** [comment]
hey @SadafKausar2025 , wait for it to be reviewed first. you can work on other issues for the time being.

**Comment by SadafKausar2025** [comment]
hi @Ultimateutkarsh11 
can you please merge this PR?

**Review by Ultimateutkarsh11 — APPROVED** [review]

**Pull request merged**
