### PR TITLE
Card design update -   #222

### PR DESCRIPTION
**Pull request by dhruv389**
I have updated Card design which looks goods compare to previous Card design.

issue no : #222 
---

**Screen shot :**
---

image

### CODE REVIEW

**Comment by dhruv389** [comment]
@FoxxPratikSau , @pallavisavant  , 

**please merge this pull request.**

**Review by Ultimateutkarsh11 — APPROVED** [review]

**Comment by pallavisavant** [comment]
I was thinking if toggle option could be provided to the user for choosing between dark mode or normal mode in notes.
How does this sound?

**Comment by dhruv389** [comment]
@pallavisavant ,
Yes , it's sound good. i can do it.

**Review by VaibhavArora314 — APPROVED** [review]

**Review by goyalh4164 — APPROVED** [review]

**Comment by goyalh4164** [comment]
@dhruv389 there is error while logging and registering the user

**Pull request merged**
