### PR TITLE
Mode Button Position Corrected

### PR DESCRIPTION
**Pull request by zalabhavy**
Hello Vaibhav,

I have successfully corrected the placement of the mode change button. Now it looks better and is also responsive according to the screen size.

For large screen:-
image

For small screen:-
image

### CODE REVIEW

**Review by Ultimateutkarsh11 — APPROVED** [review]

**Review by goyalh4164 — APPROVED** [review]

**Comment by pallavisavant** [comment]
I  feel its not completely aligned though.
Firstly 'testimonials' section is not aligned with others, the icon should come beside it and not on top.
Secondly 'login' and 'register' are not on same line as 'why us' and 'about us'

Can you also attach the existing website screenshot to this PR, or create separate issue and link it over here.
@zalabhavy 

Thanks

**Comment by zalabhavy** [comment]
This problem is in existing website it is not created by me please check this existing website.
image
In this issue i want to make mode change button position to right top corner so i do only that part that is looks like
image
If you want to align whole navbar perfectly i will open new issue but before it please merge this because it takes time and hard work for making a single change.

**Comment by zalabhavy** [comment]
@pallavisavant also for small size this is picture of existing website before i make any change
image

**Comment by Ultimateutkarsh11** [comment]
@zalabhavy I'm merging this pull request, if you want you can also raise a new issue to align all the contents of the navbar.

**Comment by zalabhavy** [comment]
@Ultimateutkarsh11  Thank you !! Already Created new issue for align issue no #314

**Pull request merged**
