### PR TITLE
Fixes #256 : Added Premium Features

### LINKED ISSUE #256: Feat: Add Pricing Section for Premium Features
### Describe the feature

This issue addresses the implementation of a pricing section within the project. It's essential to introduce a premium tier with exclusive offerings to enhance users' note-taking experience. The pricing section will serve as a gateway for users to access these premium features.

### Add ScreenShots

1.  Introduce a "Pricing" button in the navigation bar.

Navigation

2. Upon clicking this button, a new page will open, displaying various plans with their corresponding features. An attached image provides an example of how this page will appear.

Price

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by AkshitGarg24**
Fixes #256 

The following changes have been made to the project:

- A "Go Pro!" button has been added to the header. Clicking this button will redirect users to the "/pro" website.
- A dedicated page has been created specifically for this purpose. This page is also responsive, meaning it will display well on all devices. You can find a reference video attached for your convenience.

https://github.com/Note-Vault/Note-Vault/assets/153659573/de6417f8-6e2d-45e2-bf19-6f341a4a1411

**REQUEST:**  I request you to kindly upgrade this issue to a required level as you can see in the attached video, it was not a level 1 issue.

Also, please label the PR and add my name in the assignees section before merging this PR.

Thank You!

### CODE REVIEW

**Comment by AkshitGarg24** [comment]
**NOTE:** In the second commit, I have removed changes from the package-lock.json file and I have updated the header also.

Screenshot 2024-06-04 220937

**Review by VaibhavArora314 — APPROVED** [review]

**Review by Ultimateutkarsh11 — APPROVED** [review]

**Comment by AkshitGarg24** [comment]
@goyalh4164 I would like to confirm that the last merged PR was not properly reviewed, resulting in significant changes to the UI of the front page. I have used the current code from home.ejs and style.css files within the project, and the UI is displaying incorrectly as shown in the attached video.


https://github.com/Note-Vault/Note-Vault/assets/153659573/aae3e80b-5fcd-4c7e-9fac-257f4da3a8d7



Could you please advise on how to resolve these conflicts? One thing I can do is I will resolve the conflicts for now and I will create a new issue for solving the problems of UI of the website.

Thank you.

**Comment by goyalh4164** [comment]
@AkshitGarg24 you can resolve the conflicts for now and create i new issue then

**Comment by AkshitGarg24** [comment]
Done @goyalh4164. Again requesting to please upgrade the level of this issue as it was not a level 1 issue.

Thank You!

**Comment by AkshitGarg24** [comment]
Resolved Conflicts @goyalh4164.

**Comment by pallavisavant** [comment]
can you create new issue and attach it over here.
Also if your interested to work on it please go ahead.
Thanks

**Comment by AkshitGarg24** [comment]
@pallavisavant @goyalh4164

I have created a new issue #433 and request that you assign it to me so I can begin working on it.

Additionally, please label this PR with 'gssoc' and add my name to the assignees section of this PR.

Thank you!

**Comment by pallavisavant** [comment]
> @pallavisavant @goyalh4164
> 
> I have created a new issue #433 and request that you assign it to me so I can begin working on it.
> 
> Additionally, please label this PR with 'gssoc' and add my name to the assignees section of this PR.
> 
> Thank you!

PR or the issue needs the label @goyalh4164 ?

**Pull request merged**
