### PR TITLE
Folder Structure Updated

### PR DESCRIPTION
**Pull request by MitulSonagara**
@Ultimateutkarsh11 I updated the file.. can you please check it if it is working or not??

### CODE REVIEW

**Comment by MitulSonagara** [comment]
Issue Number #22

**Comment by MitulSonagara** [comment]
@VaibhavArora314 please review it and let me know if any other changes are there

**Comment by VaibhavArora314** [comment]
i think you have missed adding all the files in the pr as only isAuthenticatedLogin.js is seen in the pr. maybe try synching your fork.

**Comment by MitulSonagara** [comment]
I am very new to this how can i do this

**Pull request closed without merging**
