### PR TITLE
Home page color is changed for one section

### PR DESCRIPTION
**Pull request by MuraliDharan7**
About section had color issue with background and text which has been changed now.

### CODE REVIEW

**Comment by goyalh4164** [comment]
@MuraliDharan7 put a screenshot of the updated color

**Comment by MuraliDharan7** [comment]
> @MuraliDharan7 put a screenshot of the updated color

Since this is Web app which runs in Browser I am not able to check the same.
can you guide me

**Comment by VaibhavArora314** [comment]
> > @MuraliDharan7 put a screenshot of the updated color
> 
> Since this is Web app which runs in Browser I am not able to check the same. can you guide me

run the application on your local machine, simply click some screenshots of the edited sections and post as comment here

**Comment by VaibhavArora314** [comment]
@MuraliDharan7 any updates?

**Comment by MuraliDharan7** [comment]
You can check the color which is changed

updated note vault

**Comment by MuraliDharan7** [comment]
Fixes #164

**Comment by Ultimateutkarsh11** [comment]
@MuraliDharan7 the current colour looks better than this one because the colour you have chosen is of very high contrast.
Try something different.

**Comment by MuraliDharan7** [comment]
Is this color okay now?
image

**Review by Ultimateutkarsh11 — APPROVED** [review]

**Comment by Ultimateutkarsh11** [comment]
@MuraliDharan7 you have created a new PR with updated colour of ''About Us'' section, so I'm closing this one.

**Pull request closed without merging**
