### PR TITLE
Navbar Updated 

### PR DESCRIPTION
**Pull request by hars-21**
Updated Navbar 
Added 2 more links - why-us, testimonials for easy user navigation.

#44 fixed

Please review

### CODE REVIEW

**Comment by VaibhavArora314** [comment]
resolve merge conflicts and post some screenshots also

**Comment by hars-21** [comment]
Screen Shot 2024-05-16 at 6 45 45 PM

**Comment by Ultimateutkarsh11** [comment]
@hars-21 your branch has conflicts in the following files:
public/style/style.css
views/home.ejs
views/note.ejs
Resolve them first.

**Comment by hars-21** [comment]
@Ultimateutkarsh11 conflicts resolved

**Review by Ultimateutkarsh11 — APPROVED** [review]

**Review by VaibhavArora314 — APPROVED** [review]

**Pull request merged**
