### PR TITLE
Updated code to get correct month (Updated card design)

### PR DESCRIPTION
**Pull request by its-AkshatJain**
You are facing login issue as i have changed the structure of Notebook.js database. you will need to clear all the entries of that database to resolve the error.

You can use db.dropDatabase() in mongosh (mongodb shell) to delete the database (notebook database).

### CODE REVIEW

**Review by goyalh4164 — APPROVED** [review]

**Review by Ultimateutkarsh11 — APPROVED** [review]

**Comment by goyalh4164** [comment]
@its-AkshatJain you have not updated the notebook schema first update that then use these values .. as of now there is no need to clear the DB.. DB will automatically adapt the new schema

**Comment by its-AkshatJain** [comment]
> @its-AkshatJain you have not updated the notebook schema first update that then use these values .. as of now there is no need to clear the DB.. DB will automatically adapt the new schema

Because of sync now my code is overwritten. But now i have corrected the code you can check now.

**Comment by Ultimateutkarsh11** [comment]
@its-AkshatJain kindly resolve the merge conflicts in the following:
public/style/style.css

**Review by VaibhavArora314 — APPROVED** [review]

**Comment by its-AkshatJain** [comment]
Please add Gssoc24 label on this PR as instructed by Gssoc organisers.

**Comment by its-AkshatJain** [comment]
Can you please tell me the reason behind sudden drop in level change
Screenshot_20240523-201118

**Pull request merged**
