### PR TITLE
CODE-OF-CONDUCT.md

### PR DESCRIPTION
**Pull request by anglerfishlyy**
**fixes#84**

**description:**

- This pull request introduces a Code of Conduct file to establish guidelines for behavior and interaction within the project's /repo's community.

-It consists of all the existing sections that has been corrected. A section of SPECIFIC GUIDELINES (that tells what the community strictly wants ) is added into it.

-By following this Code of Conduct, we will be able to maintain the values of diversity, integrity, and mutual respect.

### CODE REVIEW

**Comment by goyalh4164** [comment]
@anglerfishlyy make the code of conduct short in description

**Comment by Ultimateutkarsh11** [comment]
@anglerfishlyy any updates?

**Comment by anglerfishlyy** [comment]
Sorry , I didn't get you. What am i supposed to do now? can you explain  what should i do now?

**Comment by goyalh4164** [comment]
@anglerfishlyy make the code of conduct shorter in the description as no one is going to read the bulky description make it precise..

**Review by Ultimateutkarsh11 — APPROVED** [review]

**Review by goyalh4164 — APPROVED** [review]

**Review by VaibhavArora314 — APPROVED** [review]

**Comment by anglerfishlyy** [comment]
please, assign @anglerfishlyy in this PR as it would not count towards leaderboard of GSSOC'24.

**Pull request merged**
