### PR TITLE
Added ABOUT SECTION

### PR DESCRIPTION
**Pull request by Dishika18**
I have added about section in the website. Please have a look and let me know if any further changes to be made.

Screenshot 2024-05-15 165556

Issue: #91

### CODE REVIEW

**Review by VaibhavArora314 — APPROVED** [review]

**Review by VaibhavArora314 — CHANGES_REQUESTED** [review]
there is no need to add nodemon in package.json

**Comment by Dishika18** [comment]
so shall i remove it from package-lock.json as well?

**Comment by VaibhavArora314** [comment]
simply run npm uninstall it will autmatically handle it

**Comment by goyalh4164** [comment]
@Dishika18 also solve the merge conflicts in your branch

**Pull request closed without merging**
