### PR TITLE
Changed the Home page UI

### PR DESCRIPTION
**Pull request by gauravtomar7**
BEFORE:
Before

AFTER: With the working buttons.
After

### CODE REVIEW

**Comment by VaibhavArora314** [comment]
this is in reference to which issue?

**Comment by goyalh4164** [comment]
@gauravtomar7 also resolve the merge conflicts and use the latest code

**Comment by Ultimateutkarsh11** [comment]
@gauravtomar7 any updates?

**Comment by VaibhavArora314** [comment]
closing this pr for now, you can raise another pr after resolving conflicts

**Pull request closed without merging**
