### PR TITLE
[Feature] : Faqs Page Added

### PR DESCRIPTION
**Pull request by dhruv8433**
@Note-Vault

- i added `/faqs` in static route so we can check output
- it look like this
image

i just added dummy question of note management 
please check this and merge it

### CODE REVIEW

**Comment by VaibhavArora314** [comment]
@dhruv8433 
as i stated in the issue #267, dont create a seperate page for this, import it as a partial in home page so it will be a section of home page.

**Comment by VaibhavArora314** [comment]
also post a screenshot of it in dark mode

**Comment by dhruv8433** [comment]
Ok got it

**Review by goyalh4164 — APPROVED** [review]

**Comment by dhruv8433** [comment]
@VaibhavArora314 

i updated and added faqs section in home page 
now it will look like 
image

and in dark mode: 
image

you can check it and merge it

**Review by VaibhavArora314 — APPROVED** [review]

**Comment by dhruv8433** [comment]
@Ultimateutkarsh11 @VaibhavArora314 

please review this and merge it

**Review by Ultimateutkarsh11 — APPROVED** [review]

**Pull request merged**
