### PR TITLE
Navbar Align In One Raw

### PR DESCRIPTION
**Pull request by zalabhavy**
Here I have Fix Navbar Alignment in one raw and it is also work in small size.

For Big Screen :

image

For Small Screen :

image

### CODE REVIEW

**Comment by zalabhavy** [comment]
There is many changes i do in code by live checking so please change level1 to level2 if it is possible thank you.

**Review by VaibhavArora314 — APPROVED** [review]

**Comment by pallavisavant** [comment]
Good work! LGTM

**Comment by zalabhavy** [comment]
@pallavisavant  Thank You !!

**Comment by zalabhavy** [comment]
@Ultimateutkarsh11 and @goyalh4164 please review and approve for merge.

**Review by Ultimateutkarsh11 — APPROVED** [review]

**Comment by zalabhavy** [comment]
@Ultimateutkarsh11 Thank you very much !!

**Pull request merged**
