### PR TITLE
Added Creation date in note

### PR DESCRIPTION
**Pull request by SamarthUrane**
Solved issue No. #54 under GSSOC'24.
Implemented a feature to include dates in notes, enhancing organization and clarity for users. This addition facilitates better time management and reference within the note-taking system.
Screenshot 2024-05-13 112223

### CODE REVIEW

**Comment by SamarthUrane** [comment]
Ok

**Comment by SamarthUrane** [comment]
> also add finish date as i specified in the issue

I have added Finish Date as well please merge this.

**Comment by SamarthUrane** [comment]
> Can you post some screenshots with an example of the finish date and updating it.

Screenshot 2024-05-13 175838
Screenshot 2024-05-13 175831
Screenshot 2024-05-13 175809

**Review by VaibhavArora314 — APPROVED** [review]
looks good to me

**Review by Ultimateutkarsh11 — APPROVED** [review]

**Review by goyalh4164 — COMMENTED** [review]
changes look good

**Pull request merged**
