### PR TITLE
Fixed the navbar link issue

### PR DESCRIPTION
**Pull request by pani2004**
Solved issue #386 

https://github.com/Note-Vault/Note-Vault/assets/154724111/04c9caf3-d314-4b53-85fa-efda89acd74a

### CODE REVIEW

**Comment by pani2004** [comment]
@goyalh4164 pls review the PR!!!

**Comment by goyalh4164** [comment]
@pani2004 still issue exists

**Comment by pani2004** [comment]
@goyalh4164 There are some merge conflicts, I am closing this PR and will generate a new PR

**Comment by goyalh4164** [comment]
@pani2004 no problem

**Pull request closed without merging**
