### PR TITLE
Background fix

### PR DESCRIPTION
**Pull request by ritu713**
I have adjusted the colour palette of the site as per discussed under issue #96 
Additionally, I have changed the fonts and layouts of divs to make sure that all buttons are working, and that the font looks good.

Below are the screenshots for the same.
image
image
image

### CODE REVIEW

**Comment by ritu713** [comment]
Hi, the latest commit includes the changes made by others.

**Review by VaibhavArora314 — APPROVED** [review]
looks good to me

**Comment by goyalh4164** [comment]
@ritu713  This branch as conflicts that must be resolved

Conflicting files
public/style/style.css
views/home.ejs

first resolve them

**Comment by ritu713** [comment]
Hey..resolved new merge conflicts.

**Pull request merged**
