### PR TITLE
font changed

### PR DESCRIPTION
**Pull request by harinisayani**
I have changed the font-style and size of the font to look modern.
Screenshot (84)
Screenshot (85)
Screenshot (86)

### CODE REVIEW

**Comment by goyalh4164** [comment]
@harinisayani  word seems good but your branch has merge conflicts first resolve them

**Comment by harinisayani** [comment]
I have solved my conflicts now.
Once check it please.

**Review by VaibhavArora314 — APPROVED** [review]

**Comment by goyalh4164** [comment]
@harinisayani  your branch has still merge conflicts

**Comment by harinisayani** [comment]
Hi
I have resolved conflicts

**Pull request merged**
