### PR TITLE
why choose notevault

### PR DESCRIPTION
**Pull request by NitinChakrawarti**
transition in why choose NoteVault is added
issue no #117

### **It looks previously**

https://github.com/Note-Vault/Note-Vault/assets/149225785/cfc1c021-0010-4af5-a85d-43e238943871

### **After animation and border**

https://github.com/Note-Vault/Note-Vault/assets/149225785/e0d1ff70-2d2f-492b-9c1a-7be947c3680c

@VaibhavArora314   Please don't forget to add label and assign this PR to me

### CODE REVIEW

**Comment by goyalh4164** [comment]
@NitinChakrawarti your PR is merged and your changes are live now in production

**Comment by NitinChakrawarti** [comment]
> @NitinChakrawarti your PR is merged and your changes are live now in production

Thank you @goyalh4164,
for wonderful opportunity to contribute.

**Comment by NitinChakrawarti** [comment]
@Ultimateutkarsh11 please assign this PR to me so i can get points.

**Comment by Ultimateutkarsh11** [comment]
@NitinChakrawarti labels have already been added to your PR and you will get points, don't worry.
Issues are assigned not PRs.

**Comment by NitinChakrawarti** [comment]
@Ultimateutkarsh11  but sir in discord one of mentors told me, to get assigned in PR

**Pull request merged**
