### PR TITLE
Login Page updated

### PR DESCRIPTION
**Pull request by hars-21**
Successfully updated UI for login page. Making it more User friendly.

### CODE REVIEW

**Review by goyalh4164 — COMMENTED** [review]
@VaibhavArora314 @Ultimateutkarsh11 review the changes

**Comment by VaibhavArora314** [comment]
Image is not showing, can u upload it again

**Comment by hars-21** [comment]
Screen Shot 2024-05-13 at 10 22 04 AM

**Review by VaibhavArora314 — APPROVED** [review]

**Comment by hars-21** [comment]
@Ultimateutkarsh11 Can you please add labels for this PR.

**Review by Ultimateutkarsh11 — APPROVED** [review]

**Pull request merged**
