### PR TITLE
Add the eye feature and click cursor in the Login page

### LINKED ISSUE #337: Feat: Add the eye feature in the Login page for the password
### Describe the feature

image
image
Add the show password feature

**Kindly assign me this issue**

### Add ScreenShots

image

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by AkhilaSunesh**
Fixes #337 

Proof:

https://github.com/Note-Vault/Note-Vault/assets/140897461/a704b56d-24b0-44b7-aa7b-7915e8666213

### CODE REVIEW

**Review by goyalh4164 — APPROVED** [review]

**Review by Ultimateutkarsh11 — APPROVED** [review]

**Review by VaibhavArora314 — APPROVED** [review]

**Comment by goyalh4164** [comment]
@AkhilaSunesh resolve the merge conflicts in package.json file

**Comment by pallavisavant** [comment]
resolve conflicts

**Comment by goyalh4164** [comment]
@AkhilaSunesh any progress?

**Comment by AkhilaSunesh** [comment]
I deleted package-lock.json file. So I guess it should be fine now

**Comment by goyalh4164** [comment]
@AkhilaSunesh still merge conflicts exist .. you can take a fresh pull then do commit

**Comment by AkhilaSunesh** [comment]
Ok I will do it soon

**Comment by AkhilaSunesh** [comment]
I have raised another pr. Please check

**Pull request closed without merging**
