### PR TITLE
update home footer

### PR DESCRIPTION
**Pull request by 05priyanshu**
Updated home footer style and made it responsive and also added this repository link to the copyright text 
Screenshot 2024-05-13 125044
Screenshot 2024-05-13 125100
Screenshot 2024-05-13 125140

### CODE REVIEW

**Comment by 05priyanshu** [comment]
@VaibhavArora314 @Ultimateutkarsh11 @goyalh4164 please review this

**Review by VaibhavArora314 — APPROVED** [review]
looks good to me

**Review by VaibhavArora314 — APPROVED** [review]

**Comment by Ultimateutkarsh11** [comment]
@05priyanshu the current text in the footer looks out of place, can you redesign the footer in the following format:
image

**Comment by goyalh4164** [comment]
@05priyanshu also there are some merge conflicts in your PR arising from views/home.ejs file .. kindly resolve them

**Comment by Ultimateutkarsh11** [comment]
@05priyanshu any updates?

**Comment by goyalh4164** [comment]
Create a new PR

**Pull request closed without merging**
